name: parcial_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  cloud_firestore: ^5.1.0
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  firebase_auth: ^5.1.2
  firebase_core: ^3.1.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.2.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  image_picker: ^1.1.2
  path: ^1.9.0
  path_provider: ^2.1.3
  sign_in_button: ^3.2.0
  uuid: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
